SELECT DISTINCT salary 
FROM employees
WHERE salary < (SELECT MAX(salary) FROM employees)
LIMIT 1;

-- WITHOUT USING ORDER FINDING SECOND HIGHEST BU FIRST FINDING FIRST HIGHEST USING MAX AND THEN LESS THAN AND LIMIT TO 1
