name: Update README with SQL Question Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update README File with SQL Links
        run: |
          python <<EOF
          import os
          from datetime import datetime

          def get_sql_links(directory="sql_queries"):
              sql_links = []
              if not os.path.exists(directory):
                  print(f"Warning: Directory '{directory}' not found.")
                  return sql_links

              for filename in os.listdir(directory):
                  if filename.endswith(".sql"):
                      question_name = filename.replace(".sql", "").replace("_", " ").title()
                      link = f"https://github.com/${{ github.repository }}/blob/main/{directory}/{filename}"
                      # Get the file's modification time
                      file_path = os.path.join(directory, filename)
                      modification_time = datetime.fromtimestamp(os.path.getmtime(file_path)).strftime("%Y-%m-%d")
                      sql_links.append((question_name, link, modification_time))

              # Sort by modification time (most recent first) and then by question name
              sql_links.sort(key=lambda x: (x[2], x[0]), reverse=True)

              return sql_links

          def update_readme(sql_links):
              with open("README.md", "w") as f:
                  f.write("Last updated on: $(date)\\n\\n")
                  f.write("## SQL Question Answers\\n\\n")
                  if sql_links:
                      f.write("| Question | Answer Link | Date Added |\n")
                      f.write("| -------- | ----------- | ---------- |\n")
                      for question, link, modification_time in sql_links:
                          f.write(f"| {question} | [{question}]({link}) | {modification_time} |\n")
                  else:
                      f.write("No SQL questions found in the sql_queries folder.\\n")

          sql_links = get_sql_links()
          update_readme(sql_links)
          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated README with SQL question links and dates" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
