    - name: Update README with SQL files
      run: |
        echo "Running SQL file detection..."
        python3 -c "
import os

project_directory = './'
sql_files = [f for f in os.listdir(project_directory) if f.endswith('.sql')]

if not sql_files:
    print('No .sql files found!')
else:
    print('Detected SQL files:', sql_files)
"
